baseURL = "https://nullframe.eu/"
languageCode = "en-us"
title = "NullFrame Intel"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  ShowReadingTime = true
  ShowToc = true
  disableThemeToggle = true
  homeInfoParams = { Title = "NULLFRAME", Content = "Strategic Analysis • OSINT • Reality Mapping" }

[menu]
  [[menu.main]]
    identifier = "reports"
    name = "Reports"
    url = "/reports/"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
theme = "PaperMod"
